### ISSUE TITLE
Контроллеры

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/HR_in_pocket#24]
- [ ] Home - главная страница и страницы с информацией по проекту #23
- [x] Account - авторизация, регистрация, профиль пользователя #19
- [ ] Tariffication - выбор тарифного плана, покупки #47
- [ ] Tasks - задания на поиск вакансий и составление резюме/сопр.писем. #48
- [ ] Область администратора/Home
